/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDienNguoiDung;



import Form.Panel_BaoCao;
import Form.Panel_HoaDon;
import Form.Panel_HoaDonBanHang;
import Form.Panel_HoaDonNhapHang;
import Form.Panel_HangHoa;
import Form.Panel_KhachHang;
import Form.Panel_NhaCungCap;

import Form.Panel_NhapKho;
import Form.Panel_QuanTri;
import Form.Panel_TaiKhoan;
import Form.Panel_ThongKe;
import Form.Panel_TimKiem;

import Form.Panel_TroGiup;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinh Duc
 */
public class GiaoDienChinh extends javax.swing.JFrame {
    public static Panel_HoaDonBanHang pn_HoaDonBanHang = new Panel_HoaDonBanHang();     //Dành cho Nhân viên bán hàng
    public static Panel_HoaDonNhapHang pn_HoaDonNhapHang= new Panel_HoaDonNhapHang();   //Dành cho Thủ kho
    public static Panel_HoaDon pn_HoaDon = new Panel_HoaDon();                          //Dành cho Giám đốc (hiển thị cả 2)
    public static Panel_HangHoa pn_HangHoa = new Panel_HangHoa();
    public static Panel_KhachHang pn_KhachHang = new Panel_KhachHang();
    public static Panel_NhapKho pn_NhapKho = new Panel_NhapKho();
    public static Panel_NhaCungCap pn_NhaCungCap = new Panel_NhaCungCap();
    public static Panel_ThongKe pn_ThongKe = new Panel_ThongKe();
    public static Panel_BaoCao pn_BaoCao = new Panel_BaoCao();
    public static Panel_QuanTri pn_QuanTri = new Panel_QuanTri();
    public static Panel_TimKiem pn_TimKiem = new Panel_TimKiem();
    public static Panel_TroGiup pn_TroGiup = new Panel_TroGiup();
    public static Panel_TaiKhoan pn_TaiKhoan = new Panel_TaiKhoan();
    
    
    

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        // ẩn hết Panel
        pn_HoaDon.setVisible(false);
        pn_HoaDonBanHang.setVisible(false);
        pn_HoaDonNhapHang.setVisible(false);
        pn_HangHoa.setVisible(false);
        pn_KhachHang.setVisible(false);
        pn_NhapKho.setVisible(false);
        pn_NhaCungCap.setVisible(false);
        pn_ThongKe.setVisible(false);
        pn_BaoCao.setVisible(false);
        pn_QuanTri.setVisible(false);
        pn_TimKiem.setVisible(false);
        pn_TroGiup.setVisible(false);
        pn_TaiKhoan.setVisible(false);
        
        
        // Phân quyền để hiển thị
        HamPhanQuyen(Main.nhanvien.getChucVu());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Panel_ChucNangNhanVien = new javax.swing.JPanel();
        lb_hoadon = new javax.swing.JLabel();
        lb_hanghoa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lb_khachhang = new javax.swing.JLabel();
        Panel_ChucNangChung = new javax.swing.JPanel();
        lb_timkiem = new javax.swing.JLabel();
        lb_dangxuat = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lb_taikhoan = new javax.swing.JLabel();
        lb_trogiup = new javax.swing.JLabel();
        Panel_ChucNangThuKho = new javax.swing.JPanel();
        lb_nhapkho = new javax.swing.JLabel();
        lb_nhacungcap = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        Panel_ChucNangGiamDoc = new javax.swing.JPanel();
        lb_nhapkho1 = new javax.swing.JLabel();
        lb_nhacungcap1 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        panel_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CỬA HÀNG ĐIỆN MÁY ES5");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Panel_ChucNangNhanVien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_hoadon.setBackground(new java.awt.Color(204, 204, 255));
        lb_hoadon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_bill.png"))); // NOI18N
        lb_hoadon.setText("Hóa đơn");
        lb_hoadon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_hoadon.setOpaque(true);
        lb_hoadon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hoadonMouseClicked(evt);
            }
        });

        lb_hanghoa.setBackground(new java.awt.Color(204, 204, 255));
        lb_hanghoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_hanghoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_hanghoa.png"))); // NOI18N
        lb_hanghoa.setText("Hàng hóa");
        lb_hanghoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_hanghoa.setOpaque(true);
        lb_hanghoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_hanghoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hanghoaMouseClicked(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lb_khachhang.setBackground(new java.awt.Color(204, 204, 255));
        lb_khachhang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_khachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_customer.png"))); // NOI18N
        lb_khachhang.setText("Khách hàng");
        lb_khachhang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_khachhang.setOpaque(true);
        lb_khachhang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_khachhangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ChucNangNhanVienLayout = new javax.swing.GroupLayout(Panel_ChucNangNhanVien);
        Panel_ChucNangNhanVien.setLayout(Panel_ChucNangNhanVienLayout);
        Panel_ChucNangNhanVienLayout.setHorizontalGroup(
            Panel_ChucNangNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ChucNangNhanVienLayout.createSequentialGroup()
                .addComponent(lb_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_hanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_ChucNangNhanVienLayout.setVerticalGroup(
            Panel_ChucNangNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(lb_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_hanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_khachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_ChucNangChung.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_timkiem.setBackground(new java.awt.Color(204, 204, 255));
        lb_timkiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_search.png"))); // NOI18N
        lb_timkiem.setText("Tìm kiếm");
        lb_timkiem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_timkiem.setOpaque(true);
        lb_timkiem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_timkiemMouseClicked(evt);
            }
        });

        lb_dangxuat.setBackground(new java.awt.Color(204, 204, 255));
        lb_dangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_signout.png"))); // NOI18N
        lb_dangxuat.setText("Đăng xuất");
        lb_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_dangxuat.setOpaque(true);
        lb_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_dangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_dangxuatMouseClicked(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lb_taikhoan.setBackground(new java.awt.Color(204, 204, 255));
        lb_taikhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_taikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_account2.png"))); // NOI18N
        lb_taikhoan.setText("Tài khoản");
        lb_taikhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_taikhoan.setOpaque(true);
        lb_taikhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_taikhoanMouseClicked(evt);
            }
        });

        lb_trogiup.setBackground(new java.awt.Color(204, 204, 255));
        lb_trogiup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_trogiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_help.png"))); // NOI18N
        lb_trogiup.setText("Trợ giúp");
        lb_trogiup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_trogiup.setOpaque(true);
        lb_trogiup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_trogiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_trogiupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ChucNangChungLayout = new javax.swing.GroupLayout(Panel_ChucNangChung);
        Panel_ChucNangChung.setLayout(Panel_ChucNangChungLayout);
        Panel_ChucNangChungLayout.setHorizontalGroup(
            Panel_ChucNangChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ChucNangChungLayout.createSequentialGroup()
                .addComponent(lb_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_trogiup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        Panel_ChucNangChungLayout.setVerticalGroup(
            Panel_ChucNangChungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_dangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_trogiup, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_ChucNangThuKho.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_nhapkho.setBackground(new java.awt.Color(204, 204, 255));
        lb_nhapkho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhapkho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_import.png"))); // NOI18N
        lb_nhapkho.setText("Nhập kho");
        lb_nhapkho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_nhapkho.setOpaque(true);
        lb_nhapkho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_nhapkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhapkhoMouseClicked(evt);
            }
        });

        lb_nhacungcap.setBackground(new java.awt.Color(204, 204, 255));
        lb_nhacungcap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhacungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_supplier.png"))); // NOI18N
        lb_nhacungcap.setText("Nhà cung cấp");
        lb_nhacungcap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_nhacungcap.setOpaque(true);
        lb_nhacungcap.setVerifyInputWhenFocusTarget(false);
        lb_nhacungcap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_nhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhacungcapMouseClicked(evt);
            }
        });

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel12.setBackground(new java.awt.Color(204, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_thongke.png"))); // NOI18N
        jLabel12.setText("Thống kê");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ChucNangThuKhoLayout = new javax.swing.GroupLayout(Panel_ChucNangThuKho);
        Panel_ChucNangThuKho.setLayout(Panel_ChucNangThuKhoLayout);
        Panel_ChucNangThuKhoLayout.setHorizontalGroup(
            Panel_ChucNangThuKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ChucNangThuKhoLayout.createSequentialGroup()
                .addComponent(lb_nhapkho, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_nhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_ChucNangThuKhoLayout.setVerticalGroup(
            Panel_ChucNangThuKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator9)
            .addComponent(lb_nhapkho, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_nhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_ChucNangGiamDoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_nhapkho1.setBackground(new java.awt.Color(204, 204, 255));
        lb_nhapkho1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhapkho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_report.png"))); // NOI18N
        lb_nhapkho1.setText("Báo cáo");
        lb_nhapkho1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_nhapkho1.setOpaque(true);
        lb_nhapkho1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_nhapkho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhapkho1MouseClicked(evt);
            }
        });

        lb_nhacungcap1.setBackground(new java.awt.Color(204, 204, 255));
        lb_nhacungcap1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nhacungcap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_admin.png"))); // NOI18N
        lb_nhacungcap1.setText("Quản trị");
        lb_nhacungcap1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_nhacungcap1.setOpaque(true);
        lb_nhacungcap1.setVerifyInputWhenFocusTarget(false);
        lb_nhacungcap1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_nhacungcap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_nhacungcap1MouseClicked(evt);
            }
        });

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout Panel_ChucNangGiamDocLayout = new javax.swing.GroupLayout(Panel_ChucNangGiamDoc);
        Panel_ChucNangGiamDoc.setLayout(Panel_ChucNangGiamDocLayout);
        Panel_ChucNangGiamDocLayout.setHorizontalGroup(
            Panel_ChucNangGiamDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ChucNangGiamDocLayout.createSequentialGroup()
                .addComponent(lb_nhapkho1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lb_nhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_ChucNangGiamDocLayout.setVerticalGroup(
            Panel_ChucNangGiamDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator11)
            .addComponent(lb_nhapkho1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lb_nhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Panel_ChucNangNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_ChucNangThuKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_ChucNangGiamDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_ChucNangChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_ChucNangNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_ChucNangThuKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_ChucNangChung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Panel_ChucNangGiamDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel_ChucNangNhanVien.getAccessibleContext().setAccessibleName("");

        panel_main.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_hanghoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hanghoaMouseClicked
        // TODO add your handling code here:pn_HoaDonBanHang.setVisible(true);
        ShowPanelViTriThu(1);
    }//GEN-LAST:event_lb_hanghoaMouseClicked

    private void lb_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_khachhangMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(2);
    }//GEN-LAST:event_lb_khachhangMouseClicked

    private void lb_dangxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_dangxuatMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Chưa xử lý, làm cái khác đi!");
    }//GEN-LAST:event_lb_dangxuatMouseClicked

    private void lb_nhapkhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhapkhoMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(3);
    }//GEN-LAST:event_lb_nhapkhoMouseClicked

    private void lb_nhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhacungcapMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(4);
    }//GEN-LAST:event_lb_nhacungcapMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(5);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void lb_nhapkho1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhapkho1MouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(6);
    }//GEN-LAST:event_lb_nhapkho1MouseClicked

    private void lb_nhacungcap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_nhacungcap1MouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(7);
    }//GEN-LAST:event_lb_nhacungcap1MouseClicked

    private void lb_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_timkiemMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(8);
    }//GEN-LAST:event_lb_timkiemMouseClicked

    private void lb_trogiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_trogiupMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(9);
    }//GEN-LAST:event_lb_trogiupMouseClicked

    private void lb_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_taikhoanMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(10);
    }//GEN-LAST:event_lb_taikhoanMouseClicked

    private void lb_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hoadonMouseClicked
        // TODO add your handling code here:
        ShowPanelViTriThu(0);
    }//GEN-LAST:event_lb_hoadonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ChucNangChung;
    private javax.swing.JPanel Panel_ChucNangGiamDoc;
    private javax.swing.JPanel Panel_ChucNangNhanVien;
    private javax.swing.JPanel Panel_ChucNangThuKho;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb_dangxuat;
    private javax.swing.JLabel lb_hanghoa;
    private javax.swing.JLabel lb_hoadon;
    private javax.swing.JLabel lb_khachhang;
    private javax.swing.JLabel lb_nhacungcap;
    private javax.swing.JLabel lb_nhacungcap1;
    private javax.swing.JLabel lb_nhapkho;
    private javax.swing.JLabel lb_nhapkho1;
    private javax.swing.JLabel lb_taikhoan;
    private javax.swing.JLabel lb_timkiem;
    private javax.swing.JLabel lb_trogiup;
    private javax.swing.JPanel panel_main;
    // End of variables declaration//GEN-END:variables

    private void HamPhanQuyen(String chucVu) {
        switch(chucVu){
            //Phân quyền tại đây:
            case "Giám đốc":    //TO DO hiển thị tất cả các chức năng
                pn_HoaDon.setVisible(true);
                panel_main.add(pn_HoaDon);
                break;
            
            case "Thủ kho":             // TODO ẩn một vài chức năng không thuộc về thủ kho
                //Ẩn chức năng của giám đốc
                Panel_ChucNangGiamDoc.setVisible(false);
                
                //Chọn loại Panel đặt vào hóa đơn
                pn_HoaDonNhapHang.setVisible(true);
                panel_main.add(pn_HoaDonNhapHang);
                break;
            case "Nhân viên bán hàng":  // TODO ẩn một vài chức năng không thuộc về nhân viên bán hàng
                //Ẩn panel chức năng của giám đốc và thủ kho
                Panel_ChucNangThuKho.setVisible(false);
                Panel_ChucNangGiamDoc.setVisible(false);
                
                //Chọn loại Panel đặt vào hóa đơn
                pn_HoaDonBanHang.setVisible(true);
                panel_main.add(pn_HoaDonBanHang);
                break;
        }
        panel_main.add(pn_HangHoa);
        panel_main.add(pn_KhachHang);
        
        panel_main.add(pn_NhapKho);
        panel_main.add(pn_NhaCungCap);
        panel_main.add(pn_ThongKe);
        panel_main.add(pn_BaoCao);
        panel_main.add(pn_QuanTri);
        panel_main.add(pn_TimKiem);
        panel_main.add(pn_TroGiup);
        panel_main.add(pn_TaiKhoan);
        
        
        pn_KhachHang.setVisible(false);
        pn_NhapKho.setVisible(false);
        pn_NhaCungCap.setVisible(false);
        pn_ThongKe.setVisible(false);
        pn_BaoCao.setVisible(false);
        pn_QuanTri.setVisible(false);
        pn_TimKiem.setVisible(false);
        pn_TroGiup.setVisible(false);
        pn_TaiKhoan.setVisible(false);
    }
    private void ShowPanelViTriThu(int index){
        for (int i = 0; i < panel_main.getComponents().length; i++)
        {
                Component cmpnt = panel_main.getComponent(i);
                if(i!=index){
                    cmpnt.setVisible(false);
                } else{
                    cmpnt.setVisible(true);
                }
        }
    }
    
}
