/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author ADMIN
 */
public class InFormTroGiup extends javax.swing.JInternalFrame {

    /**
     * Creates new form InFormTaiKhoan
     */
    public InFormTroGiup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlHuongDan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlTroGiup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Trợ giúp");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Nguyễn Đình Đức");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 120, 114, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Phạm Ngọc Đan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(400, 150, 106, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText("Trần Tiến Đạt");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 180, 92, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Đinh Hoàng Phú");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 210, 104, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Phan Văn Thịnh");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 240, 103, 19);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 51));
        jLabel11.setText("Liên Hệ:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 280, 53, 19);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chương Trình Quản Lý Siêu Thị Điện Máy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 30, 469, 33);

        jlHuongDan.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jlHuongDan.setForeground(new java.awt.Color(102, 0, 0));
        jlHuongDan.setText("<html> <a href=\\\"\\\">Hướng dẫn sử dụng</a></html>");
        jlHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHuongDanMouseClicked(evt);
            }
        });
        getContentPane().add(jlHuongDan);
        jlHuongDan.setBounds(220, 320, 130, 19);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoset.png"))); // NOI18N
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 190, 216);

        jlTroGiup.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jlTroGiup.setForeground(new java.awt.Color(102, 0, 51));
        jlTroGiup.setText("<html> <a href=\\\"\\\">Trogiup@.com</a></html>");
        jlTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTroGiupMouseClicked(evt);
            }
        });
        getContentPane().add(jlTroGiup);
        jlTroGiup.setBounds(280, 280, 96, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 51));
        jLabel3.setText("Giảng viên hướng dẫn:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 90, 147, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("TS. Phạm Doãn Tĩnh");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 90, 137, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 51));
        jLabel5.setText("Nhóm thực hiện:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 120, 109, 19);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dhbk.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, -4, 610, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlTroGiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTroGiupMouseClicked
         try {
          Desktop.getDesktop().mail(new URI("mailto:thinhphan011098@gmail.com?subject=TRO_GIUP_PHAN_MEM_QUAN_LY_SIEU_THI_DIEN_MAY"));
        } catch (URISyntaxException | IOException ex) {
          // lỗi
        }
    }//GEN-LAST:event_jlTroGiupMouseClicked

    private void jlHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHuongDanMouseClicked
        try {
                    Desktop.getDesktop().browse(new URI("https://www.facebook.com/phanvanthinh98"));
                } catch (IOException | URISyntaxException e1) {
                    e1.printStackTrace();
                }
    }//GEN-LAST:event_jlHuongDanMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlHuongDan;
    private javax.swing.JLabel jlTroGiup;
    // End of variables declaration//GEN-END:variables
}
