// Phan Văn Thinh code 15-11-2019
package Form;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dinh Duc
 */
public class Panel_TroGiup extends javax.swing.JPanel {

    /**
     * Creates new form Panel_chose1
     */
    public Panel_TroGiup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlTroGiup = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlHuongDan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ SIÊU THỊ ĐIỆN MÁY");
        add(jLabel1);
        jLabel1.setBounds(390, 50, 534, 31);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Giảng viên hướng dẫn:");
        add(jLabel2);
        jLabel2.setBounds(326, 148, 191, 31);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Nhóm thực hiện:");
        add(jLabel3);
        jLabel3.setBounds(326, 200, 191, 31);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Nguyễn Đình Đức");
        add(jLabel4);
        jLabel4.setBounds(595, 200, 191, 31);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Phan Văn Thịnh");
        add(jLabel5);
        jLabel5.setBounds(595, 304, 191, 31);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Phạm Ngọc Đan");
        add(jLabel6);
        jLabel6.setBounds(595, 353, 191, 31);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Đinh Hoàng Phú");
        add(jLabel7);
        jLabel7.setBounds(595, 402, 191, 31);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("20167138");
        add(jLabel8);
        jLabel8.setBounds(830, 200, 191, 31);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Trần Tiến Đạt");
        add(jLabel9);
        jLabel9.setBounds(595, 253, 191, 31);

        jlTroGiup.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jlTroGiup.setForeground(new java.awt.Color(255, 102, 0));
        jlTroGiup.setText("<html> <a href=\\\"\\\">Trogiup@gmail</a></html>");
        jlTroGiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTroGiupMouseClicked(evt);
            }
        });
        add(jlTroGiup);
        jlTroGiup.setBounds(626, 483, 191, 31);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Liên hệ: ");
        add(jLabel11);
        jLabel11.setBounds(521, 484, 87, 31);

        jlHuongDan.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jlHuongDan.setForeground(new java.awt.Color(255, 102, 0));
        jlHuongDan.setText("<html> <a href=\\\"\\\">Hướng dẫn sử dụng</a></html>");
        jlHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlHuongDanMouseClicked(evt);
            }
        });
        add(jlHuongDan);
        jlHuongDan.setBounds(521, 533, 191, 31);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("TS. Phạm Doãn Tĩnh");
        add(jLabel13);
        jLabel13.setBounds(595, 148, 191, 31);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("20160885");
        add(jLabel14);
        jLabel14.setBounds(830, 356, 80, 24);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("20163166");
        add(jLabel15);
        jLabel15.setBounds(830, 405, 80, 24);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("20163930");
        add(jLabel16);
        jLabel16.setBounds(830, 307, 80, 24);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("20160964");
        add(jLabel17);
        jLabel17.setBounds(830, 256, 80, 24);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoset.png"))); // NOI18N
        jLabel18.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel18);
        jLabel18.setBounds(0, 0, 193, 184);

        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anh_bkhn.png"))); // NOI18N
        add(jLabel20);
        jLabel20.setBounds(0, 0, 1240, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jlTroGiupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTroGiupMouseClicked
       try {
          Desktop.getDesktop().mail(new URI("mailto:thinhphan011098@gmail.com?subject=TRO_GIUP_PHAN_MEM_QUAN_LY_SIEU_THI_DIEN_MAY"));
        } catch (URISyntaxException | IOException ex) {
          JOptionPane.showMessageDialog(this, "Loi ket noi");
        }
    }//GEN-LAST:event_jlTroGiupMouseClicked

    private void jlHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlHuongDanMouseClicked
        try {
                    Desktop.getDesktop().browse(new URI("https://www.facebook.com/phanvanthinh98"));
                } catch (IOException | URISyntaxException e1) {
                    e1.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Loi ket noi");
                }
    }//GEN-LAST:event_jlHuongDanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlHuongDan;
    private javax.swing.JLabel jlTroGiup;
    // End of variables declaration//GEN-END:variables
}
