/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author Dinh Duc
 */
public class Panel_HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form Panel_chose1
     */
    public Panel_HoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbed_HoaDon = new javax.swing.JTabbedPane();

        Panel_HoaDonBanHang hd_banhang = new Panel_HoaDonBanHang();
        Panel_HoaDonNhapHang hd_nhapHang = new Panel_HoaDonNhapHang();
        tabbed_HoaDon.add("Bán hàng",hd_banhang);
        tabbed_HoaDon.add("Nhập hàng",hd_nhapHang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbed_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbed_HoaDon;
    // End of variables declaration//GEN-END:variables
}
